services:
  db:
    container_name: money-postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - moneyvolume:/data/postgres
    ports:
      - "5432:5432"

volumes:
  moneyvolume: